spring.application.name=grimoire

spring.datasource.url=jdbc:mysql://localhost:3306/grimoire?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.error.include-stacktrace=always