package generation.grimoire.enumeration;

//Pour le calcul des statistiques
public enum Source {
    CASTER_POWER,
    TARGET_POWER,
    CASTER_PHYSICAL_POWER,
    TARGET_PHYSICAL_POWER,
    CASTER_MANA_MAX,
    TARGET_MANA_MAX,
    CASTER_MANA_MISSING,
    TARGET_MANA_MISSING,
    CASTER_MANA_CURRENT,
    TARGET_MANA_CURRENT,
    CASTER_HEALTH_MAX,
    TARGET_HEALTH_MAX,
    CASTER_HEALTH_MISSING,
    TARGET_HEALTH_MISSING,
    CASTER_HEALTH_CURRENT,
    TARGET_HEALTH_CURRENT
}
