package generation.grimoire.enumeration;

public enum Source {
    CASTER_POWER,
    TARGET_POWER,
    CASTER_MANA_MAX,
    TARGET_MANA_MAX,
    TARGET_MANA_MISSING,
    CASTER_MANA_MISSING,
    TARGET_HEALTH_MAX,
    CASTER_HEALTH_MAX,
    TARGET_HEALTH_MISSING,
    CASTER_HEALTH_MISSING
}
