package generation.grimoire.enumeration;

public enum StatType {
    SPEED,
    MANA,
    HEALTH,
    CRIT,
    ARMURE,
    RESISTANCE,
    POWER,
    STRENGTH,
    BURN,
    POISON,
    DAMAGE_TAKEN_MAGIC,
    DAMAGE_TAKEN_PHYSIC,
    DAMAGE_TAKEN_BRUT,
    DAMAGE_GIVEN_MAGIC,
    DAMAGE_GIVEN_PHYSIC,
    DAMAGE_GIVEN_BRUT,
    HEAL_RECEIVED,
    SHIELD_RECEIVED,
    HEAL_GIVEN,
    SHIELD_GIVEN,
    DAMAGE_GIVEN_MAGIC_TO_SHIELD,
    DAMAGE_GIVEN_PHYSIC_TO_SHIELD,
    SHIELD_PENETRATION,
    SHIELD_PIERCED,
    AME_DETACHEE
}
